require "rake/testtask"
require "rubocop/rake_task"
require "bundler/gem_tasks"

RuboCop::RakeTask.new(:lint) do |t|
  t.options = ["--display-cop-names"]
end

Rake::TestTask.new do |t|
  t.libs = ["lib", "test"]
  t.test_files = FileList["test/*_test.rb"]
end

task :version, [:v] do |t, args|
  out = "module Forticons\n"\
    "  VERSION = \"#{args[:v]}\".freeze\n"\
    "end"
  File.open(File.expand_path("../lib/forticons/version.rb", __FILE__), "w") { |file| file.puts out }
end

desc "Run tests"
task default: :test
