require "rake/testtask"
require "bundler/gem_tasks"

task :version, [:v] do |t, args|
  out = "module ForticonsHelper\n"\
    "  VERSION = \"#{args[:v]}\".freeze\n"\
    "end"
  File.open(File.expand_path("../lib/forticons_helper/version.rb", __FILE__), "w") do |file|
    file.puts out
  end

  ["forticons_helper.gemspec", "Gemfile"].each do |filename|
    gs = File.read(File.expand_path("../#{filename}", __FILE__))
    File.open(File.expand_path("../#{filename}", __FILE__), "w") do |file|
      file.puts gs.gsub(/"forticons", "[^"]+"/, "\"forticons\", \"#{args[:v]}\"")
    end
  end
end

Rake::TestTask.new do |t|
  t.libs = ["lib", "test"]
  t.test_files = FileList["test/*_test.rb"]
  t.warning = false
end

desc "Run tests"
task default: :test
