source "https://rubygems.org"

gemspec

gem "octicons", path: "../octicons"
gem "rails"

group :development, :test do
  gem "minitest"
  gem "rake"
  gem "rubocop", "0.59"
  gem "rubocop-github", "0.12.0"
end
