# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "openproject-octicons", "19.8.0"

group :development, :test do
  gem "minitest"
  gem "rake"
  gem "rubocop-github", "0.20.0"
end
