import fs from 'node:fs/promises'
import {createRequire} from 'node:module'
import path from 'node:path'
import babel from '@babel/core'
import data from '../../build/data.json' with {type: 'json'}

const {types: t} = babel
const require = createRequire(import.meta.url)
const generate = require('@babel/generator').default
const SOURCE_DIRECTORY = path.resolve(import.meta.dirname, '../src')
const GENERATED_DIRECTORY = path.join(SOURCE_DIRECTORY, 'generated')

await fs.rm(GENERATED_DIRECTORY, {force: true, recursive: true})
await fs.mkdir(GENERATED_DIRECTORY, {recursive: true})

const BUCKET_SIZE = 40
const modules = partition(Object.values(data), BUCKET_SIZE).map((icons, index) => {
  const filepath = path.join(GENERATED_DIRECTORY, `icons-${(index + 1).toString().padStart(2, '0')}.tsx`)
  const imports = [
    t.importDeclaration(
      [t.importSpecifier(t.identifier('createIconReference'), t.identifier('createIconReference'))],
      t.stringLiteral('../IconReference.js'),
    ),
  ]

  const components = icons.flatMap(icon => {
    const symbolName = `${pascalCase(icon.name)}Symbol`
    const referenceName = `${pascalCase(icon.name)}IconReference`
    const symbols = Object.entries(icon.heights).map(([height, size]) => {
      const jsx = t.jsxElement(
        t.jsxOpeningElement(t.jsxIdentifier('symbol'), [
          t.jsxAttribute(t.jsxIdentifier('id'), t.stringLiteral(`symbol-octicon-${icon.name}-${height}`)),
          t.jsxAttribute(t.jsxIdentifier('viewBox'), t.stringLiteral(`0 0 ${size.width} ${height}`)),
        ]),
        t.jsxClosingElement(t.jsxIdentifier('symbol')),
        svgToJSX(size.ast),
      )
      return {
        height,
        width: size.width,
        jsx,
      }
    })
    const iconReference = t.variableDeclaration('const', [
      t.variableDeclarator(
        t.arrayPattern([t.identifier(symbolName), t.identifier(referenceName)]),
        t.addComment(
          t.callExpression(t.identifier('createIconReference'), [
            t.objectExpression([
              t.objectProperty(t.identifier('id'), t.stringLiteral(`symbol-octicon-${icon.name}`)),
              t.objectProperty(t.identifier('name'), t.stringLiteral(referenceName)),
              t.objectProperty(
                t.identifier('sizes'),
                t.objectExpression(
                  symbols.map(symbol =>
                    t.objectProperty(
                      t.stringLiteral(symbol.height),
                      t.objectExpression([
                        t.objectProperty(t.identifier('definition'), symbol.jsx),
                        t.objectProperty(
                          t.stringLiteral('id'),
                          t.stringLiteral(`symbol-octicon-${icon.name}-${symbol.height}`),
                        ),
                        t.objectProperty(t.stringLiteral('width'), t.numericLiteral(symbol.width)),
                      ]),
                    ),
                  ),
                ),
              ),
            ]),
          ]),
          'leading',
          '#__PURE__',
        ),
      ),
    ])

    return [t.exportNamedDeclaration(iconReference)]
  })

  const program = t.addComment(
    t.program([...imports, ...components]),
    'leading',
    `This file is auto-generated by 'script/build.js'. Do not edit directly.`,
  )

  return {
    filepath,
    contents: generate(program).code,
    exports: icons.flatMap(icon => [`${pascalCase(icon.name)}IconReference`, `${pascalCase(icon.name)}Symbol`]),
  }
})

for (const mod of modules) {
  await fs.writeFile(mod.filepath, mod.contents)
}

const octiconsSymbolsPropsExportSpecifier = t.exportSpecifier(
  t.identifier('OcticonSymbolsProps'),
  t.identifier('OcticonSymbolsProps'),
)
octiconsSymbolsPropsExportSpecifier.exportKind = 'type'

const octiconsReferencePropsExportSpecifier = t.exportSpecifier(
  t.identifier('OcticonReferenceProps'),
  t.identifier('OcticonReferenceProps'),
)
octiconsReferencePropsExportSpecifier.exportKind = 'type'

const octiconSymbolExportSpecifier = t.exportSpecifier(t.identifier('OcticonSymbol'), t.identifier('OcticonSymbol'))
octiconSymbolExportSpecifier.exportKind = 'type'

const createIconReferenceOptionsExportSpecifier = t.exportSpecifier(
  t.identifier('CreateIconReferenceOptions'),
  t.identifier('CreateIconReferenceOptions'),
)
createIconReferenceOptionsExportSpecifier.exportKind = 'type'

const index = t.addComment(
  t.program([
    t.exportNamedDeclaration(
      null,
      [
        t.exportSpecifier(t.identifier('OcticonSymbols'), t.identifier('OcticonSymbols')),
        octiconsSymbolsPropsExportSpecifier,
      ],
      t.stringLiteral('../OcticonSymbols.js'),
    ),
    t.exportNamedDeclaration(
      null,
      [
        t.exportSpecifier(t.identifier('createIconReference'), t.identifier('createIconReference')),
        createIconReferenceOptionsExportSpecifier,
        octiconSymbolExportSpecifier,
      ],
      t.stringLiteral('../IconReference.js'),
    ),
    t.exportNamedDeclaration(null, [octiconsReferencePropsExportSpecifier], t.stringLiteral('../types.js')),
    ...modules.map(mod => {
      return t.exportNamedDeclaration(
        null,
        mod.exports.map(exportName => t.exportSpecifier(t.identifier(exportName), t.identifier(exportName))),
        t.stringLiteral(`./${path.basename(mod.filepath, path.extname(mod.filepath))}.js`),
      )
    }),
  ]),
  'leading',
  `This file is auto-generated by 'script/build.js'. Do not edit directly.`,
)

await fs.writeFile(path.join(GENERATED_DIRECTORY, 'index.ts'), generate(index).code)

function partition(items, size) {
  const result = []
  let bucket = []

  for (const item of items) {
    if (bucket.length >= size) {
      result.push(bucket)
      bucket = []
    }

    bucket.push(item)
  }

  if (bucket.length > 0) {
    result.push(bucket)
  }

  return result
}

function pascalCase(value) {
  return value.replace(/(^|-)([a-z])/g, (_, __, character) => character.toUpperCase())
}

function svgToJSX(node) {
  if (node.type === 'element') {
    const children = node.children.map(svgToJSX)

    if (node.name === 'svg') {
      if (children.length === 0) {
        throw new Error('No children available for icon')
      }

      return children.flat()
    }

    const attrs = Object.entries(node.attributes).map(([key, value]) => {
      if (typeof value !== 'string') {
        throw new Error(`Unknown value type: ${value}`)
      }
      return t.jsxAttribute(t.jsxIdentifier(key), t.stringLiteral(value))
    })
    const openingElement = t.jsxOpeningElement(t.jsxIdentifier(node.name), attrs, children.length === 0)
    const closingElement = t.jsxClosingElement(t.jsxIdentifier(node.name))

    if (children.length > 0) {
      return [t.jsxElement(openingElement, closingElement, children.flat(), false)]
    }

    return [t.jsxElement(openingElement, closingElement, [], true)]
  }

  throw new Error(`Unknown type: ${node.type}`)
}
