source "https://rubygems.org"

gemspec

gem "octicons", path: "../octicons_gem"
gem "rails"

group :development, :test do
  gem "minitest"
  gem "rake"
  gem "rubocop", "0.50"
  gem "rubocop-github", "0.5.0"
end
