# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "openproject-octicons", "19.13.0"
gem "rails"

group :development, :test do
  gem "minitest"
  gem "rake"
  gem "rubocop-github", "0.20.0"
end
