import fs from 'node:fs/promises'
import {createRequire} from 'node:module'
import path from 'node:path'
import babel from '@babel/core'
import type babelGenerate from '@babel/generator'
import {pascalCase} from 'change-case'
import data from '@primer/octicons/build/data.json' with {type: 'json'}

const {types: t} = babel
const require = createRequire(import.meta.url)
const generate: typeof babelGenerate = require('@babel/generator').default
const SOURCE_DIRECTORY = path.resolve(import.meta.dirname, '../src')
const GENERATED_DIRECTORY = path.join(SOURCE_DIRECTORY, 'generated')

await fs.mkdir(GENERATED_DIRECTORY, {recursive: true})

const modules = Object.values(data).map(icon => {
  const imports = [
    // import {createIconReference} from '../IconReference'
    t.importDeclaration(
      [t.importSpecifier(t.identifier('createIconReference'), t.identifier('createIconReference'))],
      t.stringLiteral('../IconReference'),
    ),
  ]
  const symbolName = `${pascalCase(icon.name)}Symbol`
  const referenceName = `${pascalCase(icon.name)}IconReference`
  const symbols = Object.entries(icon.heights).map(([height, size]) => {
    const jsx = t.jsxElement(
      t.jsxOpeningElement(
        t.jsxIdentifier('symbol'),
        [
          t.jsxAttribute(t.jsxIdentifier('id'), t.stringLiteral(`symbol-octicon-${icon.name}-${height}`)),
          t.jsxAttribute(t.jsxIdentifier('viewBox'), t.stringLiteral(`0 0 ${size.width} ${height}`)),
        ],
        false,
      ),
      t.jsxClosingElement(t.jsxIdentifier('symbol')),
      svgToJSX(size.ast),
    )
    return {
      height,
      width: size.width,
      jsx,
    }
  })
  const iconReference = t.variableDeclaration('const', [
    t.variableDeclarator(
      t.arrayPattern([t.identifier(symbolName), t.identifier(referenceName)]),
      t.addComment(
        t.callExpression(t.identifier('createIconReference'), [
          t.objectExpression([
            t.objectProperty(t.identifier('id'), t.stringLiteral(`symbol-octicon-${icon.name}`)),
            t.objectProperty(t.identifier('name'), t.stringLiteral(referenceName)),
            t.objectProperty(
              t.identifier('sizes'),
              t.objectExpression(
                symbols.map(symbol =>
                  t.objectProperty(
                    t.stringLiteral(symbol.height),
                    t.objectExpression([
                      t.objectProperty(t.identifier('definition'), symbol.jsx),
                      t.objectProperty(
                        t.stringLiteral('id'),
                        t.stringLiteral(`symbol-octicon-${icon.name}-${symbol.height}`),
                      ),
                      t.objectProperty(t.stringLiteral('width'), t.numericLiteral(symbol.width)),
                    ]),
                  ),
                ),
              ),
            ),
          ]),
        ]),
        'leading',
        '#__PURE__',
      ),
    ),
  ])
  const filepath = path.join(GENERATED_DIRECTORY, `${pascalCase(icon.name)}.tsx`)
  const body = [...imports, t.exportNamedDeclaration(iconReference)]
  const program = t.addComment(
    t.program(body),
    'leading',
    ` This file is auto-generated by 'script/build.ts'. Do not edit directly. `,
  )

  return {
    filepath,
    contents: generate(program).code,
    exports: [symbolName, referenceName],
  }
})

for (const mod of modules) {
  await fs.writeFile(mod.filepath, mod.contents)
}

const indexFilePath = path.join(SOURCE_DIRECTORY, 'generated', 'index.ts')

const octiconsSymbolsPropsExportSpecifier = t.exportSpecifier(
  t.identifier('OcticonSymbolsProps'),
  t.identifier('OcticonSymbolsProps'),
)
octiconsSymbolsPropsExportSpecifier.exportKind = 'type'

const octiconsReferencePropsExportSpecifier = t.exportSpecifier(
  t.identifier('OcticonReferenceProps'),
  t.identifier('OcticonReferenceProps'),
)
octiconsReferencePropsExportSpecifier.exportKind = 'type'

const octiconSymbolExportSpecifier = t.exportSpecifier(t.identifier('OcticonSymbol'), t.identifier('OcticonSymbol'))
octiconSymbolExportSpecifier.exportKind = 'type'

const createIconReferenceOptionsExportSpecifier = t.exportSpecifier(
  t.identifier('CreateIconReferenceOptions'),
  t.identifier('CreateIconReferenceOptions'),
)
createIconReferenceOptionsExportSpecifier.exportKind = 'type'

const index = t.addComment(
  t.program([
    t.exportNamedDeclaration(
      null,
      [
        t.exportSpecifier(t.identifier('OcticonSymbols'), t.identifier('OcticonSymbols')),
        octiconsSymbolsPropsExportSpecifier,
      ],
      t.stringLiteral('../OcticonSymbols'),
    ),
    t.exportNamedDeclaration(
      null,
      [
        t.exportSpecifier(t.identifier('createIconReference'), t.identifier('createIconReference')),
        createIconReferenceOptionsExportSpecifier,
        octiconSymbolExportSpecifier,
      ],
      t.stringLiteral('../IconReference'),
    ),
    t.exportNamedDeclaration(null, [octiconsReferencePropsExportSpecifier], t.stringLiteral('../types')),
    ...modules.map(mod => {
      return t.exportNamedDeclaration(
        null,
        mod.exports.map(exportName => t.exportSpecifier(t.identifier(exportName), t.identifier(exportName))),
        t.stringLiteral(`./${path.basename(mod.filepath, path.extname(mod.filepath))}`),
      )
    }),
  ]),
  'leading',
  `This file is auto-generated by 'script/build.ts'. Do not edit directly.`,
)

await fs.writeFile(indexFilePath, generate(index).code)

type SVGASTNode = {
  type: string
  name: string
  attributes: Record<string, string>
  children: Array<SVGASTNode>
}

function svgToJSX(node: SVGASTNode): Array<babel.types.JSXElement> {
  if (node.type === 'element') {
    const children = node.children.map(svgToJSX)

    if (node.name === 'svg') {
      if (children.length === 0) {
        throw new Error(`No children available for icon`)
      }

      return children.flat()
    }

    const attrs = Object.entries(node.attributes).map(([key, value]) => {
      if (typeof value !== 'string') {
        throw new Error(`Unknown value type: ${value}`)
      }
      return t.jsxAttribute(t.jsxIdentifier(key), t.stringLiteral(value))
    })
    const openingElement = t.jsxOpeningElement(t.jsxIdentifier(node.name), attrs, children.length === 0)
    const closingElement = t.jsxClosingElement(t.jsxIdentifier(node.name))

    if (children.length > 0) {
      return [t.jsxElement(openingElement, closingElement, children.flat(), false)]
    }

    return [t.jsxElement(openingElement, closingElement, [], true)]
  }

  throw new Error(`Unknown type: ${node.type}`)
}
