#!/bin/bash
set -e

if [[ "$CI" != "true" ]]; then
  echo "(bailing: not in CI)"
  exit
fi

branch=$TRAVIS_PULL_REQUEST_BRANCH
event=$TRAVIS_EVENT_TYPE

# only publish canary releases on PRs against dev
if [[ "$event" = "pull_request" ]] && [[ !("$branch" =~ ^release-.*) ]] && [[ !("$branch" = "master") ]];
then

  echo "🐦  Publishing PR (canary) release..."

  $(npm bin)/lerna publish --npm-tag=alpha --canary --exact --skip-git --yes
fi
