#!/bin/bash
set -e

# Clear the build dir
rm -rf build
rm -rf lib/**/build

# Clear old gems
rm -f lib/**/*.gem

./script/export
# ./script/build-json

cp -R build lib/octicons_node/
cp -R build lib/octicons_gem/
