#!/bin/bash
set -e

# Clear the build dir
rm -rf build
rm -rf lib/**/build

# Export svg slices from sketch document
sketchtool export slices octicons-master.sketch --output=build/svg/

# Export pngs
# sketchtool export slices octicons-master.sketch --output=build/png/ --formats="png,pdf,eps"

# Minify the svg
$(npm bin)/svgo -f build/svg/ --config='{"plugins":[{"removeTitle": true},{"removeStyleElement": true},{"removeAttrs": { "attrs": ["id", "class", "data-name", "fill"] }},{"removeEmptyContainers": true},{"sortAttrs": true},{"removeUselessDefs": true},{"removeEmptyText": true},{"removeEditorsNSData": true},{"removeEmptyAttrs": true},{"removeHiddenElems": true}]}'

./script/build-json

cp -R build lib/octicons_node/
