#!/bin/bash
set -e

$(npm bin)/lerna clean

# files="**.log lib/**/build lib/**/.bundle node_modules lib/**/node_modules/ **/vendor *.lock **/package-lock.json"
#
# for file in ${files}; do
#   for paths in $()
#   rm -rf ${file}
# done
