#!/usr/bin/env node
const SVGO = require('svgo')
const got = require('got')
const spinner = require('ora')('')
const {ensureDir, removeSync, writeFile} = require('fs-extra')
const {join, resolve} = require('path')
const {figma} = require('../package.json')
const {fetchSSLFix, loadYAML, progress, queueTasks} = require('./utils.js')

const {FIGMA_DOMAIN = 'api.figma.com', FIGMA_TOKEN, FIGMA_FILE_KEY} = process.env

// Fail if there's no figma file key
let figmaFileKey = FIGMA_FILE_KEY
if (!figmaFileKey) {
  try {
    figmaFileKey = figma.url.match(/file\/([a-z0-9]+)\//i)[1]
  } catch (e) {
    spinner.fail('Cannot find figma.url key in package.json!')
    throw e
  }
}

const svgo = new SVGO(loadYAML(join(process.cwd(), '.svgo.yml')))

// Where we're putting the exported SVG and data.json
// so the libraries can use it
const outputDir = resolve(__dirname, '../build')
spinner.info(`output dir: ${outputDir}`)

removeSync(outputDir)
ensureDir(join(outputDir, 'svg')).then(() => {
  if (FIGMA_TOKEN) {
    spinner.info(`Exporting octicons from ${figma.url} file`)
    getFigmaComponents(figmaFileKey).catch(error => {
      spinner.fail(`Error fetching components from Figma: ${error}`)
      process.exitCode = 1
    })
  } else {
    getUnpkgData().catch(error => {
      spinner.fail(`Error fetching data from unpkg.com: ${error}`)
      process.exitCode = 1
    })
  }
})

function getFigmaComponents(figmaFileKey) {
  let dCount = 0
  let oCount = 0
  spinner.info('Getting components from the figma file')
  spinner.start(`Contacting ${FIGMA_DOMAIN}`)
  return got
    .get(`${FIGMA_DOMAIN}/v1/files/${figmaFileKey}`, {
      headers: {
        'Content-Type': 'application/json',
        'x-figma-token': FIGMA_TOKEN
      },
      json: true
    })
    .then(response => {
      spinner.start('Processing response')

      const components = {}
      function check(c) {
        if (c.type === 'COMPONENT') {
          const {name, id} = c
          const {description = ''} = response.body.components[c.id]
          const {width, height} = c.absoluteBoundingBox
          // Keywords extracted from description when that's ready
          let keywords = description.match(/^keywords: (.+)$/im)
          // If we have a match, get keywords and split by comma
          keywords = keywords ? keywords.pop().split(', ') : []

          components[name] = {
            name,
            figma: {
              id,
              file: figmaFileKey
            },
            keywords,
            width,
            height
          }
        } else if (c.children) {
          // eslint-disable-next-line github/array-foreach
          c.children.forEach(check)
        }
      }

      // eslint-disable-next-line github/array-foreach
      response.body.document.children.forEach(check)
      oCount = Object.values(components).length
      if (oCount === 0) {
        throw Error('No octicons found!')
      }
      spinner.succeed(`${oCount} icons found in the figma file`)
      return components
    })
    .then(components => {
      const icons = Object.values(components)
      // Make a query string with all the component ids
      const componentIds = icons.map(c => c.figma.id).join(',')
      // Request all the image export URLs from figma
      return getFigmaImageUrls(componentIds)
        .then(images => {
          spinner.info('Downloading SVG files from Figma (AWS)')
          spinner.start('')

          return queueTasks(
            icons.map(icon => () => {
              return got
                .get(images[icon.figma.id], {
                  headers: {
                    'Content-Type': 'images/svg+xml'
                  }
                })
                .on('downloadProgress', () => {
                  spinner.text = `${progress(dCount, oCount)} Downloading ${icon.name} icon`
                })
                .then(response => {
                  const svg = response.body
                  dCount++
                  return svgo
                    .optimize(svg, {})
                    .then(optimized => {
                      icon.path = optimized.data.slice(optimized.data.indexOf('>') + 1).slice(0, -6)
                      const dir = resolve(outputDir, 'svg')
                      return ensureDir(dir).then(() => writeFile(join(dir, `${icon.name}.svg`), optimized.data, 'utf8'))
                    })
                    .catch(err => {
                      console.error('Something went wrong optimizing the svg data!', err)
                      process.exit(1)
                    })
                })
            })
          )
        })
        .then(() => {
          spinner.stopAndPersist({
            text: `${progress(dCount, oCount)} ${Object.keys(components).length} icons downloaded`
          })
          spinner.info(`Writing data out to ${outputDir}/data.json`)
          return writeFile(resolve(outputDir, 'data.json'), JSON.stringify(components), 'utf8')
            .then(() => {
              console.warn('\nAll done! Icons successfully exported.')
            })
        })
    })
}

function getFigmaImageUrls(componentIds) {
  spinner.info('Exporting figma components as SVG')
  return got
    .get(`${FIGMA_DOMAIN}/v1/images/${figmaFileKey}`, {
      query: {
        ids: componentIds,
        format: 'svg'
      },
      headers: {
        'Content-Type': 'application/json',
        'x-figma-token': FIGMA_TOKEN
      },
      json: true
    })
    .then(response => {
      if (response.body.err) {
        throw response.body.err
      } else {
        spinner.succeed('Successfully exported components')
        return response.body.images
      }
    })
}

function getUnpkgData() {
  const {name, version} = require('../node/octicons/package.json')
  const url = `https://raw.githubusercontent.com/primer/octicons/v${version}/package.json`
  return got
    .get(url, {json: true})
    .then(response => response.body)
    .then(pkg => {
      // same file; good to go!
      if (pkg.figma.url === figma.url) {
        const baseURL = `https://unpkg.com/${name}@${version}/build/`
        spinner.info('Getting components from unpkg.com')
        spinner.start('Fetching data.json...')
        return fetchAndWrite(baseURL, 'data.json', outputDir)
          .then(JSON.parse)
          .then(data => {
            const icons = Object.values(data)
            const total = icons.length
            let loaded = 0
            spinner.start('Fetching SVG files...')
            return queueTasks(
              icons.map(icon => () => {
                loaded++
                spinner.text = `${progress(loaded, total)} Downloading icon: ${icon.name}`
                return fetchAndWrite(baseURL, `svg/${icon.name}.svg`, outputDir)
              })
            ).then(() => icons)
          })
          .then(icons => {
            spinner.info(`Wrote ${icons.length} icons to ${outputDir}/svg`)
            spinner.succeed(`Fetched ${icons.length} icons from unpkg.com/${name}@${version}`)
            return icons
          })
      } else {
        spinner.fail(
          `figma.url mismatch in package.json:\n  "${figma.url}" (local)\n  "${pkg.figma.url}" (from: ${url})`
        )
        process.exitCode = 1
      }
    })
}

function fetchAndWrite(baseURL, file, dirname) {
  return fetchSSLFix(join(baseURL, file)).then(body => {
    return writeFile(join(dirname, file), body, 'utf8')
      .then(() => body)
  })
}
