#!/bin/bash
set -e

outdir=lib/svg
rm -rf $outdir
mkdir -p $outdir

# Export svg slices from sketch document
sketchtool export slices octicons-master.sketch --output=$outdir

# Export pngs
# sketchtool export slices octicons-master.sketch --output=build/png/ --formats="png,pdf,eps"

# Minify the svg
$(npm bin)/svgo -f $outdir
