#!/bin/bash
set -e

if [[ "$CI" != "true" ]]; then
  echo "(bailing: not in CI)"
  exit
fi

rubygems=$(jq -r .rubygems package.json)

(gem build $rubygems.gemspec; gem push $rubygems-*.gem) & wait

retVal=$?
if [ ! $? -eq 0 ]; then
    ../../script/notify failure
fi
exit $retVal
