#!/bin/bash
set -e
echo "📦  Publishing latest release..."

if [[ "$CI" != "true" ]]; then
  echo "(bailing: not in CI)"
  exit
fi

$(npm bin)/lerna publish --exact --since \"v$(npm info octicons version)\"
