#!/bin/bash
set -e

octicons_v=$(jq -r .dependencies.octicons_gem package.json)

perl -pi -e "s/VERSION = \"[^\"]+\"/VERSION = \"${npm_package_version}\"/" ./lib/**/version.rb
perl -pi -e "s/\"octicons\", \"[^\"]+\"/\"octicons\", \"${octicons_v}\"/" ./Gemfile ./*.gemspec

git add ./lib/**/version.rb ./Gemfile ./*.gemspec
