#!/bin/bash
set -e

PACKAGE_VERSION=$(jq '.version' --raw-output ./package.json)

PACKAGE_VERSION=$(echo $PACKAGE_VERSION | sed -e 's/^0\.0\.0./0.0.0.pre./g')
PACKAGE_VERSION=$(echo $PACKAGE_VERSION | sed -e 's/-rc/.pre/g')

echo "************* Building v$PACKAGE_VERSION *************"

echo "**************** Copying assets files to build directory ****************"
cp -R ../build lib/

echo "**************** Versioning ****************"
bundle exec rake version\["$PACKAGE_VERSION"\]

echo "**************** Building ****************"
bundle exec rake build
