name: Package API
on:
  pull_request_target:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update:
    if: >
      github.event.pull_request.head.repo.full_name == 'primer/octicons' &&
      contains(github.event.pull_request.labels.*.name, 'api changes approved') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Install workspace dependencies
        working-directory: lib/octicons_react
        run: yarn
      - name: Build project
        run: yarn build
      - name: Build package
        working-directory: lib/octicons_react
        run: yarn build
      - name: Update snapshots
        working-directory: lib/octicons_react
        run: yarn test -u
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(project): update @primer/octicons-react Public API'
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'api changes approved'
