on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: read
  checks: write
  statuses: write

name: Octicons Publish
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - run: cp -r icons lib/build/svg
      - uses: actions/upload-artifact@v4
        with:
          name: octicons
          path: ./lib/build
  gem:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: octicons
          path: ./lib/build
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Build and publish octicons gem
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          PACKAGE_NAME: octicons_gem
        run: |
          set -e

          PACKAGE_VERSION=$(ruby -rjson -e "puts JSON.parse(File.read('package.json'))['version']")
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/^0\.0\.0./0.0.0.pre./g')
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/-rc/.pre/g')

          echo "************* Building v$PACKAGE_VERSION *************"

          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build lib/

          perl -pi -e "s/\"octicons\", \"[^\"]+\"/\"octicons\", \"${PACKAGE_VERSION}\"/" ./Gemfile ./*.gemspec

          echo "**************** Installing ****************"
          bundle install

          echo "**************** Versioning ****************"
          bundle exec rake version\["$PACKAGE_VERSION"\]

          bundle update

          echo "**************** Building ****************"
          bundle exec rake build
          GEM_PUSH_OUTPUT=$(gem push pkg/*.gem 2>&1) || {
            echo "$GEM_PUSH_OUTPUT"
            echo "$GEM_PUSH_OUTPUT" | grep -q "Repushing of gem versions is not allowed" || exit 1
          }
      - run: ls ./lib/octicons_gem/pkg
      - uses: actions/upload-artifact@v4
        with:
          name: octicons_gem
          path: ./lib/octicons_gem/pkg
  helper:
    runs-on: ubuntu-latest
    needs: gem
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/download-artifact@v4
        with:
          name: octicons_gem
          path: ./lib/octicons_helper/vendor/cache
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Build and publish octicons helper gem
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          PACKAGE_NAME: octicons_helper
        run: |
          set -e

          PACKAGE_VERSION=$(ruby -rjson -e "puts JSON.parse(File.read('package.json'))['version']")
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/^0\.0\.0./0.0.0.pre./g')
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/-rc/.pre/g')

          echo "************* Building v$PACKAGE_VERSION *************"

          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build lib/

          perl -pi -e "s/\"octicons\", \"[^\"]+\"/\"octicons\", \"${PACKAGE_VERSION}\"/" ./Gemfile ./*.gemspec

          echo "**************** Installing ****************"
          bundle install

          echo "**************** Versioning ****************"
          bundle exec rake version\["$PACKAGE_VERSION"\]

          bundle update

          echo "**************** Building ****************"
          bundle exec rake build
          GEM_PUSH_OUTPUT=$(gem push pkg/*.gem 2>&1) || {
            echo "$GEM_PUSH_OUTPUT"
            echo "$GEM_PUSH_OUTPUT" | grep -q "Repushing of gem versions is not allowed" || exit 1
          }
  jekyll:
    runs-on: ubuntu-latest
    needs: gem
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/download-artifact@v4
        with:
          name: octicons_gem
          path: ./lib/octicons_jekyll/vendor/cache
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Build and publish octicons jekyll gem
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}
          PACKAGE_NAME: octicons_jekyll
        run: |
          set -e

          PACKAGE_VERSION=$(ruby -rjson -e "puts JSON.parse(File.read('package.json'))['version']")
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/^0\.0\.0./0.0.0.pre./g')
          PACKAGE_VERSION=$(echo "$PACKAGE_VERSION" | sed -e 's/-rc/.pre/g')

          echo "************* Building v$PACKAGE_VERSION *************"

          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_TOKEN}
          EOF
          chmod 0600 ~/.gem/credentials

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build lib/

          perl -pi -e "s/\"octicons\", \"[^\"]+\"/\"octicons\", \"${PACKAGE_VERSION}\"/" ./Gemfile ./*.gemspec

          echo "**************** Installing ****************"
          bundle install

          echo "**************** Versioning ****************"
          bundle exec rake version\["$PACKAGE_VERSION"\]

          bundle update

          echo "**************** Building ****************"
          bundle exec rake build
          GEM_PUSH_OUTPUT=$(gem push pkg/*.gem 2>&1) || {
            echo "$GEM_PUSH_OUTPUT"
            echo "$GEM_PUSH_OUTPUT" | grep -q "Repushing of gem versions is not allowed" || exit 1
          }
  node:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build and publish @primer/octicons
        env:
          PACKAGE_NAME: octicons_node
        run: |
          set -e

          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          echo "************* Building v$PACKAGE_VERSION *************"

          PUBLISH_TAG=latest
          if [[ "$PACKAGE_VERSION" =~ ^0\.0\.0\- ]]; then
            PUBLISH_TAG=canary
          elif [[ "$PACKAGE_VERSION" =~ \-rc ]]; then
            PUBLISH_TAG=next
          fi

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build/ .

          echo "**************** Installing ****************"
          npm install --legacy-peer-deps

          echo "**************** Building ****************"
          npm run build

          {
            echo "**************** Publishing ****************"
            npm version --allow-same-version "$PACKAGE_VERSION" && npm publish --tag "$PUBLISH_TAG" --access public
          } || exit 0
  react:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
        with:
          name: octicons
          path: ./lib/build
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build @primer/octicons-react
        env:
          PACKAGE_NAME: octicons_react
        run: |
          set -e

          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          echo "************* Building v$PACKAGE_VERSION *************"

          PUBLISH_TAG=latest
          if [[ "$PACKAGE_VERSION" =~ ^0\.0\.0\- ]]; then
            PUBLISH_TAG=canary
          elif [[ "$PACKAGE_VERSION" =~ \-rc ]]; then
            PUBLISH_TAG=next
          fi

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build/ .

          echo "**************** Installing ****************"
          npm install --legacy-peer-deps

          echo "**************** Building ****************"
          npm run build

          {
            echo "**************** Publishing ****************"
            npm version --allow-same-version "$PACKAGE_VERSION" && npm publish --tag "$PUBLISH_TAG" --access public
          } || exit 0
      - name: Build @primer/styled-octicons
        env:
          PACKAGE_NAME: octicons_styled
        run: |
          set -e

          PACKAGE_VERSION=$(node -p "require('./package.json').version")

          echo "************* Building v$PACKAGE_VERSION *************"

          PUBLISH_TAG=latest
          if [[ "$PACKAGE_VERSION" =~ ^0\.0\.0\- ]]; then
            PUBLISH_TAG=canary
          elif [[ "$PACKAGE_VERSION" =~ \-rc ]]; then
            PUBLISH_TAG=next
          fi

          cd "./lib/$PACKAGE_NAME"

          echo "**************** Copying assets files to build directory ****************"
          cp -R ../build/ .

          echo "**************** Installing ****************"
          npm install --legacy-peer-deps

          echo "**************** Building ****************"
          npm run build

          {
            echo "**************** Publishing ****************"
            npm version --allow-same-version "$PACKAGE_VERSION" && npm publish --tag "$PUBLISH_TAG" --access public
          } || exit 0
