name: Ruby
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: gem:octicons
            directory: ./lib/octicons_gem
          - name: gem:octicons_helper
            directory: ./lib/octicons_helper
          - name: gem:octicons_jekyll
            directory: ./lib/octicons_jekyll
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Build Octicons assets
        run: |
          npm run build
          cp -r icons lib/build/svg
          cp -r lib/build lib/octicons_gem/lib/
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install octicons dependencies
        working-directory: ./lib/octicons_gem
        run: bundle install
      - name: Test octicons
        working-directory: ./lib/octicons_gem
        run: bundle exec rake test
      - name: Build octicons
        working-directory: ./lib/octicons_gem
        run: bundle exec rake build
      - name: Prepare dependent gems
        run: |
          mkdir -p lib/octicons_helper/vendor/cache lib/octicons_jekyll/vendor/cache
          cp lib/octicons_gem/pkg/*.gem lib/octicons_helper/vendor/cache/
          cp lib/octicons_gem/pkg/*.gem lib/octicons_jekyll/vendor/cache/
      - name: Install octicons_helper dependencies
        working-directory: ./lib/octicons_helper
        run: bundle config set --local disable_checksum_validation true && bundle install
      - name: Test octicons_helper
        working-directory: ./lib/octicons_helper
        run: bundle exec rake test
      - name: Install octicons_jekyll dependencies
        working-directory: ./lib/octicons_jekyll
        run: bundle config set --local disable_checksum_validation true && bundle install
      - name: Test octicons_jekyll
        working-directory: ./lib/octicons_jekyll
        run: bundle exec rake test
